#!/bin/bash
# Shared harness paths for Claude and Codex.
# Source this file after PROJECT_ROOT is set.

HARNESS_ROOT="${HARNESS_ROOT:-$PROJECT_ROOT/.harness}"
HARNESS_WORKTREES_DIR="$HARNESS_ROOT/worktrees"
HARNESS_EXEC_PLANS_DIR="$HARNESS_ROOT/exec-plans"
HARNESS_LOGS_DIR="$HARNESS_ROOT/logs"
HARNESS_ACTIVE_TASK_FILE="$HARNESS_ROOT/active-task"

LEGACY_HARNESS_ROOT="$PROJECT_ROOT/.claude"
LEGACY_WORKTREES_DIR="$LEGACY_HARNESS_ROOT/worktrees"
LEGACY_EXEC_PLANS_DIR="$LEGACY_HARNESS_ROOT/exec-plans"
LEGACY_LOGS_DIR="$LEGACY_HARNESS_ROOT/logs"
LEGACY_ACTIVE_TASK_FILE="$LEGACY_HARNESS_ROOT/active-task"
