import SwiftUI

public extension DesignSystemTypography {
    enum Pretendard {
        public static let bold11_5 = DesignSystemTypography(family: .pretendard(.bold), size: 11.5)
        public static let bold12 = DesignSystemTypography(family: .pretendard(.bold), size: 12)
        public static let bold12_5 = DesignSystemTypography(family: .pretendard(.bold), size: 12.5)
        public static let bold13 = DesignSystemTypography(family: .pretendard(.bold), size: 13)
        public static let bold14 = DesignSystemTypography(family: .pretendard(.bold), size: 14)
        public static let bold15 = DesignSystemTypography(family: .pretendard(.bold), size: 15)
        public static let bold16 = DesignSystemTypography(family: .pretendard(.bold), size: 16)
        public static let bold17 = DesignSystemTypography(family: .pretendard(.bold), size: 17)
        public static let bold17_5 = DesignSystemTypography(family: .pretendard(.bold), size: 17.5)
        public static let bold18 = DesignSystemTypography(family: .pretendard(.bold), size: 18)
        public static let bold26 = DesignSystemTypography(family: .pretendard(.bold), size: 26)
        public static let extraBold10 = DesignSystemTypography(family: .pretendard(.extraBold), size: 10)
        public static let extraBold11 = DesignSystemTypography(family: .pretendard(.extraBold), size: 11)
        public static let extraBold12 = DesignSystemTypography(family: .pretendard(.extraBold), size: 12)
        public static let extraBold17 = DesignSystemTypography(family: .pretendard(.extraBold), size: 17)
        public static let extraBold18 = DesignSystemTypography(family: .pretendard(.extraBold), size: 18)
        public static let extraBold20 = DesignSystemTypography(family: .pretendard(.extraBold), size: 20)
        public static let extraBold22 = DesignSystemTypography(family: .pretendard(.extraBold), size: 22)
        public static let extraBold23 = DesignSystemTypography(family: .pretendard(.extraBold), size: 23)
        public static let extraBold26 = DesignSystemTypography(family: .pretendard(.extraBold), size: 26)
        public static let extraBold28 = DesignSystemTypography(family: .pretendard(.extraBold), size: 28)
        public static let extraBold29 = DesignSystemTypography(family: .pretendard(.extraBold), size: 29)
        public static let extraBold30 = DesignSystemTypography(family: .pretendard(.extraBold), size: 30)
        public static let extraBold32 = DesignSystemTypography(family: .pretendard(.extraBold), size: 32)
        public static let extraBold33 = DesignSystemTypography(family: .pretendard(.extraBold), size: 33)
        public static let extraBold40 = DesignSystemTypography(family: .pretendard(.extraBold), size: 40)
        public static let extraBold46 = DesignSystemTypography(family: .pretendard(.extraBold), size: 46)
        public static let extraBold52 = DesignSystemTypography(family: .pretendard(.extraBold), size: 52)
        public static let extraBold60 = DesignSystemTypography(family: .pretendard(.extraBold), size: 60)
        public static let medium12 = DesignSystemTypography(family: .pretendard(.medium), size: 12)
        public static let medium12_5 = DesignSystemTypography(family: .pretendard(.medium), size: 12.5)
        public static let medium13 = DesignSystemTypography(family: .pretendard(.medium), size: 13)
        public static let medium14 = DesignSystemTypography(family: .pretendard(.medium), size: 14)
        public static let medium14_5 = DesignSystemTypography(family: .pretendard(.medium), size: 14.5)
        public static let medium15 = DesignSystemTypography(family: .pretendard(.medium), size: 15)
        public static let medium16 = DesignSystemTypography(family: .pretendard(.medium), size: 16)
        public static let regular12 = DesignSystemTypography(family: .pretendard(.regular), size: 12)
        public static let regular13 = DesignSystemTypography(family: .pretendard(.regular), size: 13)
        public static let regular13_5 = DesignSystemTypography(family: .pretendard(.regular), size: 13.5)
        public static let regular14 = DesignSystemTypography(family: .pretendard(.regular), size: 14)
        public static let regular15 = DesignSystemTypography(family: .pretendard(.regular), size: 15)
        public static let semiBold11 = DesignSystemTypography(family: .pretendard(.semiBold), size: 11)
        public static let semiBold12 = DesignSystemTypography(family: .pretendard(.semiBold), size: 12)
        public static let semiBold13 = DesignSystemTypography(family: .pretendard(.semiBold), size: 13)
        public static let semiBold13_5 = DesignSystemTypography(family: .pretendard(.semiBold), size: 13.5)
        public static let semiBold14 = DesignSystemTypography(family: .pretendard(.semiBold), size: 14)
        public static let semiBold14_5 = DesignSystemTypography(family: .pretendard(.semiBold), size: 14.5)
        public static let semiBold15 = DesignSystemTypography(family: .pretendard(.semiBold), size: 15)
        public static let semiBold16 = DesignSystemTypography(family: .pretendard(.semiBold), size: 16)
        public static let semiBold17 = DesignSystemTypography(family: .pretendard(.semiBold), size: 17)
        public static let semiBold18 = DesignSystemTypography(family: .pretendard(.semiBold), size: 18)
        public static let medium16_5 = DesignSystemTypography(family: .pretendard(.medium), size: 16.5)
        public static let regular10 = DesignSystemTypography(family: .pretendard(.regular), size: 10)
        public static let regular16 = DesignSystemTypography(family: .pretendard(.regular), size: 16)
        public static let regular20 = DesignSystemTypography(family: .pretendard(.regular), size: 20)
        public static let semiBold28 = DesignSystemTypography(family: .pretendard(.semiBold), size: 28)
        public static let semiBold32 = DesignSystemTypography(family: .pretendard(.semiBold), size: 32)
        public static let regular11 = DesignSystemTypography(family: .pretendard(.regular), size: 11)
    }
}
